---
title: "Analysis of Alcohol Consumption Patterns"
output:
  flexdashboard::flex_dashboard:
    theme: bootstrap
    storyboard: true
    navbar:
      - { title: "Hayaku",  align: right}
      - { title: "Kexin Xu, Smriti Vinayak Bhat, Yalong liu, Yin Shan Ho",  align: right}
---
   

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

Introduction {.tabset}
======================

Column {.tabset}
-------------------------------------

### Background




Column {.tabset} {data-width=100}
-------------------------------------

### Approach of Project

The report will be collating specific sections of this data pertaining to countrywise policy responses, consumption pattern, youth and alcohol, levels of consumption and harms and consequences.

### Information on Data

This report is being created using the data from the GISAH (Global Information System on Alcohol and Health) tool of the World Health Organisation. GISAH tool helps monitor trends relating to alcohol consumption across various age groups, side effects (harm caused) as well as the policy responses by different countries.


Analysis {.tabset}
======================

Column {.tabset}
-------------------------------------

### Research Question 1 

**How has the popularity of each type of alcohol changed over the years for different countries and have the local favorites of earlier decades been overtaken by other types of alcohol in terms of consumption?**

### Research Question 2 

**Does alcohol take more lives in traffic crashes or illnesses and which countries suffer more from alcohol-related cases?**

### Research Question 3

**What are the recurring patterns of policy responses across different countries in the world and how has it impacted the consumption of alcohol?**

### Research Question 4

**Do drinking age restrictions and legal blood alcohol concentration (BAC) limits for young drivers have any effect on adolescents’ drinking among countries?**

### Research Question 5

**What are the trends in youth drinking issues over the years?**


Findings {.tabset}
======================

Limitations {.tabset}
======================

Conclusion {.tabset}
======================

References {.tabset}
======================

GHO | global information system on alcohol and Health (gisah) | global information system on alcohol and health. (n.d.). Retrieved May 09, 2021, from https://apps.who.int/gho/data/node.gisah.GISAH?lang=en&amp;showonly=GISAH